# Generated by Django 5.0.3 on 2026-07-08 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('session_date', models.DateField()),
                ('session_number', models.IntegerField()),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academics.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academics.subject')),
            ],
            options={
                'unique_together': {('subject', 'session_date', 'session_number', 'semester', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'unique_together': {('attendance_session', 'student')},
            },
        ),
    ]
